apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: first-service
                port:
                  number: 8080